[test.simple-positive]
input = "[[1,1],[2,2],[3,3]]"
output = "3"

[test.simple-negative]
input = "[[1,1],[3,2],[5,3],[4,1],[2,3],[1,4]]"
output = "4"

[test.horizontal]
input = "[[1,3],[2,3],[5,3],[2,4],[5,4]]"
output = "3"

[test.vertical]
input = "[[1,3],[1,4],[1,6],[2,4],[2,8]]"
output = "3"

[test.empty]
input = "[]"
output = "0"

[test.one-point]
input = "[[0,0]]"
output = "1"
